# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(default='0 lei', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('img_path', models.ImageField(upload_to='products/media/products/images/')),
                ('img_description', models.CharField(max_length=200)),
                ('related', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='related_rel_+', to='products.Product')),
            ],
        ),
    ]
